Update azure-pipelines.yaml for Azure Pipelines

diff --git a/pipeline-example2-terraform/azure/azure-pipelines.yaml b/pipeline-example2-terraform/azure/azure-pipelines.yaml
--- a/pipeline-example2-terraform/azure/azure-pipelines.yaml
+++ b/pipeline-example2-terraform/azure/azure-pipelines.yaml
@@ -36,7 +36,7 @@ stages:
           inputs:
             script: ls $(Build.SourcesDirectory)            
         - task: Docker@2.240.3
-          displayName: Build and Push
+          displayName: Build
           inputs:
             containerRegistry: 'container-registry-connection'
             repository: '$(project-name-dev)/$(image-name)'
@@ -50,34 +50,26 @@ stages:
             containerRegistry: 'container-registry-connection'
             repository: '$(project-name-dev)/$(image-name)'
             tags: $(Build.BuildId)
-      - job: deploy
-        displayName: Update Gitops Repo
-        steps:        
-          - checkout: github_repo_devops
-            displayName: Checkout Gitops Repository
-            persistCredentials: true
-          - task: Bash@3
-            displayName: Update image SHA signature
-            inputs:
-              targetType: inline
-              script: |
-                echo $(project-name-dev)
-                echo $(image-name)
-                ls $(Build.SourcesDirectory)
-                app_line_number=$(grep -n "name: test" $(Build.SourcesDirectory)/react-app-example/manifests/prod/kustomization.yaml | cut -d ":" -f1)
-                if [ -z "$app_line_number" ]; then
-                  echo "Will not replace the image in the kustomization.yaml file"
-                else
-                    image_line_number=$((app_line_number + 1))
-                    sed -i "${image_line_number}s,.*,   newName: ${image}," $(Build.SourcesDirectory)/react-app-example/manifests/prod/kustomization.yaml
-                    if [ $? -ne 0 ]; then
-                        echo "Error in replacing the image in the kustomization.yaml file"
-                    else
-                        echo "Image replaced in the Devkustomization.yaml file"
-                        image_tage_line_number=$((app_line_number + 2))
-                        sed -i "${image_tage_line_number}s,.*,   newTag: $image_tag," /root/repos/azure-dev-ops-with-managed-openshift-gitops/react-app-example/manifests/prod/kustomization.yaml
-                        echo "Image Tag replaced in the Prod kustomization.yaml file"        
-                    fi
-                fi
-
-
+        - task: Bash@3
+          displayName: Update image SHA signature
+          inputs:
+            targetType: inline
+            script: |
+              echo $(project-name-dev)
+              echo $(image-name)
+              ls $(Build.SourcesDirectory)
+              app_line_number=$(grep -n "name: test" $(Build.SourcesDirectory)/react-app-example/manifests/prod/kustomization.yaml | cut -d ":" -f1)
+              if [ -z "$app_line_number" ]; then
+                echo "Will not replace the image in the kustomization.yaml file"
+              else
+                  image_line_number=$((app_line_number + 1))
+                  sed -i "${image_line_number}s,.*,   newName: ${image}," $(Build.SourcesDirectory)/react-app-example/manifests/prod/kustomization.yaml
+                  if [ $? -ne 0 ]; then
+                      echo "Error in replacing the image in the kustomization.yaml file"
+                  else
+                      echo "Image replaced in the Dev kustomization.yaml file"
+                      image_tage_line_number=$((app_line_number + 2))
+                      sed -i "${image_tage_line_number}s,.*,   newTag: $image_tag," /root/repos/azure-dev-ops-with-managed-openshift-gitops/react-app-example/manifests/prod/kustomization.yaml
+                      echo "Image Tag replaced in the Prod kustomization.yaml file"        
+                  fi
+              fi
